@uri = http://localhost:3000/api/comments

# Get all comments for a post
get {{uri}}/post/6

###
# Get a specific comment
get {{uri}}/1

###
# Post a comment
post {{uri}}
Content-Type: application/json

{
    "postId": 6,
    "authorId": 6,
    "content": "Test comment 3."
}

###
# Update a comment
put {{uri}}
Content-Type: application/json

{
    "commentId": 4,
    "content": "This is my absolute favorite post."
}

###
# Delete a comment by id
delete {{uri}}/5

###
# Delete all comments by post
delete {{uri}}/post/6