@uri = http://localhost:3000/api/posts


# Get all posts
get {{uri}}

###
# Get post by id
get {{uri}}/12

###
# Create post
post {{uri}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImR1ZGVtYW4iLCJlbWFpbCI6ImR1ZGVAbWFuLmlvIiwicmVnaXN0ZXJlZE9uIjoiMjAyNC0xMi0yOVQxMTo1NzoyOS4zODFaIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzM1ODI2NTIyfQ.sF6M1JPH_F2mXzF_7AFAQ5C5xE-Ud-gTFM442nXq-ZQ

{
    "title": "I Have the Authority",
    "content": "I have the right to post!",
    "authorId": 6
}

###
# Update title & content of post
put {{uri}}
Content-Type: application/json

{
    "id": 6,
    "title": "Test Post the Second",
    "content": "This is a post about nothing in particular."
}

###
# Update the title only
put {{uri}}
Content-Type: application/json

{
    "id": 6,
    "title": "Test Post Part II"
}

###
# Update the content only
put {{uri}}
Content-Type: application/json

{
    "id": 6,
    "content": "This post will complete the system of German idealism."
}

###
# Toggle post isPublished status
put {{uri}}/published-status/1

###
# Add a tag
put {{uri}}/add-tag
Content-Type: application/json

{
    "postId": 12,
    "tag": "programming"
}

###
# Remove a tag
put {{uri}}/remove-tag
Content-Type: application/json

{
    "postId": 12,
    "tag": "programming"
}

###
# Auth test
post {{uri}}/test
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImR1ZGVtYW4iLCJlbWFpbCI6ImR1ZGVAbWFuLmlvIiwicmVnaXN0ZXJlZE9uIjoiMjAyNC0xMi0yOVQxMTo1NzoyOS4zODFaIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzM1ODI2NTIyfQ.sF6M1JPH_F2mXzF_7AFAQ5C5xE-Ud-gTFM442nXq-ZQ
