@uri = http://localhost:3000/api/posts


# Get all posts
get {{uri}}

###
# Get post by id
get {{uri}}/12

###
# Create post
post {{uri}}
Content-Type: application/json

{
    "title": "Test Post Six",
    "content": "This post has one tag.",
    "authorId": 5,
    "tag": "philosophy"
}

###
# Update title & content of post
put {{uri}}
Content-Type: application/json

{
    "id": 6,
    "title": "Test Post the Second",
    "content": "This is a post about nothing in particular."
}

###
# Update the title only
put {{uri}}
Content-Type: application/json

{
    "id": 6,
    "title": "Test Post Part II"
}

###
# Update the content only
put {{uri}}
Content-Type: application/json

{
    "id": 6,
    "content": "This post will complete the system of German idealism."
}

###
# Toggle post isPublished status
put {{uri}}/published-status/1

###
# Add a tag
put {{uri}}/add-tag
Content-Type: application/json

{
    "postId": 12,
    "tag": "programming"
}

###
# Remove a tag
put {{uri}}/remove-tag
Content-Type: application/json

{
    "postId": 12,
    "tag": "programming"
}