@uri = http://localhost:3000/api/tags

# Get all tags (with posts for corresponding tag)
get {{uri}}/

###
# Get a list of tags
get {{uri}}/list

###
# Get tag by id
get {{uri}}/2

###
# Post a tag
post {{uri}}
Content-Type: application/json

{
    "name": "history"
}

###
# Update a tag
put {{uri}}
Content-Type: application/json

{
    "id": 2,
    "name": "Philosophy"
}

###
# Delete tag by id
delete {{uri}}/3

###
# Delete all tags
delete {{uri}}